using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraFollowTarget : MonoBehaviour
{
   
    private Transform target; // El objeto a seguir
    private float speed = 5f; // Velocidad de seguimiento
    private Vector3 offset; // Offset opcional para ajustar la posici칩n de la c치mara

    private void LateUpdate()
    {
        if (target != null)
        {
            // Ajusta la posici칩n con el offset
            Vector3 desiredPosition = target.position + offset;
            transform.position = Vector3.Lerp(transform.position, desiredPosition, speed * Time.deltaTime);
            
            // Hace que la c치mara siempre mire al target
            transform.LookAt(target);
        }
    }
}
